import concurrent.futures
import logging
import os

from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.processing_utils import load_processor, load_tokenizer

__all__ = ["generate_rollout"]

logger = logging.getLogger(__name__)


TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False

# Worker-local state (initialized per process)
_worker_tokenizer = None
_worker_mask_generator = None

# Global executor state (reused across generate_rollout calls)
_global_executor = None
_global_executor_max_workers = None


def _worker_initializer(hf_checkpoint: str, loss_mask_type: str, trust_remote_code: bool = True):
    """Initialize tokenizer and mask generator in worker process.

    This function runs once per worker process when it starts. Each worker process
    gets its own independent tokenizer to avoid pickling issues.

    Args:
        hf_checkpoint: Path to HuggingFace model checkpoint
        loss_mask_type: Type of loss mask generator (e.g., "qwen3_fix")
        trust_remote_code: Whether to trust remote code when loading tokenizer
    """
    global _worker_tokenizer, _worker_mask_generator
    if _worker_tokenizer is None:
        _worker_tokenizer = load_tokenizer(hf_checkpoint, trust_remote_code=trust_remote_code)
        _worker_mask_generator = MultiTurnLossMaskGenerator(_worker_tokenizer, tokenizer_type=loss_mask_type)


def _process_sample_minimal(sample_data: tuple) -> tuple:
    """Process a single sample in worker process with minimal data.

    This optimized version only receives necessary fields (prompt, metadata)
    instead of the entire Sample object, reducing serialization overhead.

    Args:
        sample_data: Tuple of (index, prompt, metadata)

    Returns:
        Tuple of (index, token_ids, response_length, loss_mask)
    """
    global _worker_tokenizer, _worker_mask_generator
    index, prompt, metadata = sample_data
    tools = metadata.get("tools", None) if metadata else None

    token_ids, loss_mask = _worker_mask_generator.get_loss_mask(prompt, tools)
    # loss_mask去除[151667, 271, 151668]
    target_sub = [151667, 271, 151668]
    token_str = ",".join(map(str, token_ids))
    target_str = ",".join(map(str, target_sub))
    if target_str in token_str:
        sub_len = len(target_sub)
        for i in range(len(token_ids)-sub_len+1):
            if token_ids[i: i+sub_len] == target_sub: loss_mask[i: i+sub_len] = [0] * sub_len
    response_length = _worker_mask_generator.get_response_lengths([loss_mask])[0]

    return index, token_ids, response_length, loss_mask[-response_length:]


def _get_or_create_executor(max_workers, hf_checkpoint, loss_mask_type):
    """Get or create global ProcessPoolExecutor.

    This function maintains a global executor that is reused across multiple
    calls to generate_rollout, avoiding the overhead of creating new worker
    processes and loading tokenizers on each call.

    Args:
        max_workers: Number of worker processes
        hf_checkpoint: Path to HuggingFace model
        loss_mask_type: Type of loss mask generator

    Returns:
        ProcessPoolExecutor instance
    """
    global _global_executor, _global_executor_max_workers

    if _global_executor is None or _global_executor_max_workers != max_workers:
        # Shutdown old executor if exists
        if _global_executor is not None:
            logger.info(f"Shutting down old executor with {_global_executor_max_workers} workers")
            _global_executor.shutdown(wait=True)

        # Create new executor
        logger.info(f"Creating global ProcessPoolExecutor with {max_workers} workers")
        _global_executor = concurrent.futures.ProcessPoolExecutor(
            max_workers=max_workers,
            initializer=_worker_initializer,
            initargs=(hf_checkpoint, loss_mask_type, True),
        )
        _global_executor_max_workers = max_workers

    return _global_executor


def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """An example to implement the generate_rollout function for an rule based rm rollout generation.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert not evaluation
    assert args.rollout_global_dataset

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    samples = data_buffer.get_samples(args.rollout_batch_size)

    # === Timing segment 1: Data preparation ===
    # Optimization: Extract only necessary fields to reduce serialization overhead
    indexed_samples = [(idx, sample.prompt, sample.metadata) for idx, (sample,) in enumerate(samples)]

    # Determine number of workers (conservative default for memory safety)
    # TODO: Implement Copy-on-Write optimization to allow more workers without memory overhead
    # See detailed implementation plan in plan file: Copy-on-Write optimization (Stage 2)
    max_workers = getattr(args, "sft_rollout_workers", None) or min(os.cpu_count(), 4)

    # === Timing segment 2: Parallel processing ===
    # Use global executor (reused across generate_rollout calls to avoid process creation overhead)
    executor = _get_or_create_executor(max_workers, args.hf_checkpoint, args.loss_mask_type)

    # Submit all tasks (using optimized minimal data function)
    futures = [executor.submit(_process_sample_minimal, sample_data) for sample_data in indexed_samples]

    # Wait for first result (measure fastest worker)
    first_future = next(concurrent.futures.as_completed(futures))
    first_result = first_future.result()

    # Collect all remaining results
    results = [first_result]
    for future in concurrent.futures.as_completed(futures):
        try:
            results.append(future.result())
        except Exception as e:
            logger.error(f"Error processing sample in worker: {e}")
            raise

    # === Timing segment 3: Post-processing ===
    results.sort(key=lambda x: x[0])  # Sort by original index

    for i, sample in enumerate(samples):
        (sample,) = sample
        _, token_ids, response_length, loss_mask = results[i]
        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = loss_mask[-response_length:]

        if i == 0 and not SAMPLE_PRINTED:
            messages = sample.prompt
            logger.info(
                f"sft_rollout::generate_rollout example data: {sample=} (raw){messages=} (raw){token_ids=} (raw){loss_mask=} {response_length=}"
            )
            SAMPLE_PRINTED = True

    return samples
